# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:01:44+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class AndroidDevice(BaseModel):
    androidModelId: Optional[str] = Field(
        None,
        description='Required. The id of the Android device to be used. Use the TestEnvironmentDiscoveryService to get supported options.',
    )
    androidVersionId: Optional[str] = Field(
        None,
        description='Required. The id of the Android OS version to be used. Use the TestEnvironmentDiscoveryService to get supported options.',
    )
    locale: Optional[str] = Field(
        None,
        description='Required. The locale the test device used for testing. Use the TestEnvironmentDiscoveryService to get supported options.',
    )
    orientation: Optional[str] = Field(
        None,
        description='Required. How the device is oriented during the test. Use the TestEnvironmentDiscoveryService to get supported options.',
    )


class AndroidDeviceList(BaseModel):
    androidDevices: Optional[List[AndroidDevice]] = Field(
        None, description='Required. A list of Android devices.'
    )


class OrchestratorOption(Enum):
    ORCHESTRATOR_OPTION_UNSPECIFIED = 'ORCHESTRATOR_OPTION_UNSPECIFIED'
    USE_ORCHESTRATOR = 'USE_ORCHESTRATOR'
    DO_NOT_USE_ORCHESTRATOR = 'DO_NOT_USE_ORCHESTRATOR'


class AndroidMatrix(BaseModel):
    androidModelIds: Optional[List[str]] = Field(
        None,
        description='Required. The ids of the set of Android device to be used. Use the TestEnvironmentDiscoveryService to get supported options.',
    )
    androidVersionIds: Optional[List[str]] = Field(
        None,
        description='Required. The ids of the set of Android OS version to be used. Use the TestEnvironmentDiscoveryService to get supported options.',
    )
    locales: Optional[List[str]] = Field(
        None,
        description='Required. The set of locales the test device will enable for testing. Use the TestEnvironmentDiscoveryService to get supported options.',
    )
    orientations: Optional[List[str]] = Field(
        None,
        description='Required. The set of orientations to test with. Use the TestEnvironmentDiscoveryService to get supported options.',
    )


class Form(Enum):
    DEVICE_FORM_UNSPECIFIED = 'DEVICE_FORM_UNSPECIFIED'
    VIRTUAL = 'VIRTUAL'
    PHYSICAL = 'PHYSICAL'
    EMULATOR = 'EMULATOR'


class FormFactor(Enum):
    DEVICE_FORM_FACTOR_UNSPECIFIED = 'DEVICE_FORM_FACTOR_UNSPECIFIED'
    PHONE = 'PHONE'
    TABLET = 'TABLET'
    WEARABLE = 'WEARABLE'


class RoboMode(Enum):
    ROBO_MODE_UNSPECIFIED = 'ROBO_MODE_UNSPECIFIED'
    ROBO_VERSION_1 = 'ROBO_VERSION_1'
    ROBO_VERSION_2 = 'ROBO_VERSION_2'


class TestState(Enum):
    TEST_STATE_UNSPECIFIED = 'TEST_STATE_UNSPECIFIED'
    VALIDATING = 'VALIDATING'
    PENDING = 'PENDING'
    RUNNING = 'RUNNING'
    FINISHED = 'FINISHED'
    ERROR = 'ERROR'
    UNSUPPORTED_ENVIRONMENT = 'UNSUPPORTED_ENVIRONMENT'
    INCOMPATIBLE_ENVIRONMENT = 'INCOMPATIBLE_ENVIRONMENT'
    INCOMPATIBLE_ARCHITECTURE = 'INCOMPATIBLE_ARCHITECTURE'
    CANCELLED = 'CANCELLED'
    INVALID = 'INVALID'


class CancelTestMatrixResponse(BaseModel):
    testState: Optional[TestState] = Field(
        None,
        description='The current rolled-up state of the test matrix. If this state is already final, then the cancelation request will have no effect.',
    )


class ClientInfoDetail(BaseModel):
    key: Optional[str] = Field(
        None, description='Required. The key of detailed client information.'
    )
    value: Optional[str] = Field(
        None, description='Required. The value of detailed client information.'
    )


class Date(BaseModel):
    day: Optional[int] = Field(
        None,
        description="Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.",
    )
    month: Optional[int] = Field(
        None,
        description='Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.',
    )
    year: Optional[int] = Field(
        None,
        description='Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.',
    )


class DeviceIpBlock(BaseModel):
    addedDate: Optional[Date] = Field(
        None, description='The date this block was added to Firebase Test Lab'
    )
    block: Optional[str] = Field(
        None, description='An IP address block in CIDR notation eg: 34.68.194.64/29'
    )
    form: Optional[Form] = Field(
        None, description='Whether this block is used by physical or virtual devices'
    )


class DeviceIpBlockCatalog(BaseModel):
    ipBlocks: Optional[List[DeviceIpBlock]] = Field(
        None, description='The device IP blocks used by Firebase Test Lab'
    )


class Distribution(BaseModel):
    marketShare: Optional[float] = Field(
        None,
        description='Output only. The estimated fraction (0-1) of the total market with this configuration.',
    )
    measurementTime: Optional[str] = Field(
        None, description='Output only. The time this distribution was measured.'
    )


class EnvironmentVariable(BaseModel):
    key: Optional[str] = Field(None, description='Key for the environment variable.')
    value: Optional[str] = Field(
        None, description='Value for the environment variable.'
    )


class FileReference(BaseModel):
    gcsPath: Optional[str] = Field(
        None,
        description='A path to a file in Google Cloud Storage. Example: gs://build-app-1414623860166/app%40debug-unaligned.apk These paths are expected to be url encoded (percent encoding)',
    )


class GoogleAuto(BaseModel):
    pass


class GoogleCloudStorage(BaseModel):
    gcsPath: Optional[str] = Field(
        None,
        description='Required. The path to a directory in GCS that will eventually contain the results for this test. The requesting user must have write access on the bucket in the supplied path.',
    )


class IntentFilter(BaseModel):
    actionNames: Optional[List[str]] = Field(
        None, description='The android:name value of the tag.'
    )
    categoryNames: Optional[List[str]] = Field(
        None, description='The android:name value of the tag.'
    )
    mimeType: Optional[str] = Field(
        None, description='The android:mimeType value of the tag.'
    )


class IosDevice(BaseModel):
    iosModelId: Optional[str] = Field(
        None,
        description='Required. The id of the iOS device to be used. Use the TestEnvironmentDiscoveryService to get supported options.',
    )
    iosVersionId: Optional[str] = Field(
        None,
        description='Required. The id of the iOS major software version to be used. Use the TestEnvironmentDiscoveryService to get supported options.',
    )
    locale: Optional[str] = Field(
        None,
        description='Required. The locale the test device used for testing. Use the TestEnvironmentDiscoveryService to get supported options.',
    )
    orientation: Optional[str] = Field(
        None,
        description='Required. How the device is oriented during the test. Use the TestEnvironmentDiscoveryService to get supported options.',
    )


class IosDeviceFile(BaseModel):
    bundleId: Optional[str] = Field(
        None,
        description='The bundle id of the app where this file lives. iOS apps sandbox their own filesystem, so app files must specify which app installed on the device.',
    )
    content: Optional[FileReference] = Field(None, description='The source file')
    devicePath: Optional[str] = Field(
        None,
        description="Location of the file on the device, inside the app's sandboxed filesystem",
    )


class IosDeviceList(BaseModel):
    iosDevices: Optional[List[IosDevice]] = Field(
        None, description='Required. A list of iOS devices.'
    )


class IosTestLoop(BaseModel):
    appBundleId: Optional[str] = Field(
        None, description='Output only. The bundle id for the application under test.'
    )
    appIpa: Optional[FileReference] = Field(
        None, description='Required. The .ipa of the application to test.'
    )
    scenarios: Optional[List[int]] = Field(
        None,
        description='The list of scenarios that should be run during the test. Defaults to the single scenario 0 if unspecified.',
    )


class IosTestSetup(BaseModel):
    additionalIpas: Optional[List[FileReference]] = Field(
        None,
        description='iOS apps to install in addition to those being directly tested.',
    )
    networkProfile: Optional[str] = Field(
        None,
        description='The network traffic profile used for running the test. Available network profiles can be queried by using the NETWORK_CONFIGURATION environment type when calling TestEnvironmentDiscoveryService.GetTestEnvironmentCatalog.',
    )
    pullDirectories: Optional[List[IosDeviceFile]] = Field(
        None,
        description="List of directories on the device to upload to Cloud Storage at the end of the test. Directories should either be in a shared directory (such as /private/var/mobile/Media) or within an accessible directory inside the app's filesystem (such as /Documents) by specifying the bundle ID.",
    )
    pushFiles: Optional[List[IosDeviceFile]] = Field(
        None,
        description='List of files to push to the device before starting the test.',
    )


class IosVersion(BaseModel):
    id: Optional[str] = Field(
        None,
        description='An opaque id for this iOS version. Use this id to invoke the TestExecutionService.',
    )
    majorVersion: Optional[int] = Field(
        None,
        description='An integer representing the major iOS version. Examples: "8", "9".',
    )
    minorVersion: Optional[int] = Field(
        None,
        description='An integer representing the minor iOS version. Examples: "1", "2".',
    )
    supportedXcodeVersionIds: Optional[List[str]] = Field(
        None, description='The available Xcode versions for this version.'
    )
    tags: Optional[List[str]] = Field(
        None,
        description='Tags for this dimension. Examples: "default", "preview", "deprecated".',
    )


class IosXcTest(BaseModel):
    appBundleId: Optional[str] = Field(
        None, description='Output only. The bundle id for the application under test.'
    )
    testSpecialEntitlements: Optional[bool] = Field(
        None,
        description='The option to test special app entitlements. Setting this would re-sign the app having special entitlements with an explicit application-identifier. Currently supports testing aps-environment entitlement.',
    )
    testsZip: Optional[FileReference] = Field(
        None,
        description='Required. The .zip containing the .xctestrun file and the contents of the DerivedData/Build/Products directory. The .xctestrun file in this zip is ignored if the xctestrun field is specified.',
    )
    xcodeVersion: Optional[str] = Field(
        None,
        description='The Xcode version that should be used for the test. Use the TestEnvironmentDiscoveryService to get supported options. Defaults to the latest Xcode version Firebase Test Lab supports.',
    )
    xctestrun: Optional[FileReference] = Field(
        None,
        description='An .xctestrun file that will override the .xctestrun file in the tests zip. Because the .xctestrun file contains environment variables along with test methods to run and/or ignore, this can be useful for sharding tests. Default is taken from the tests zip.',
    )


class LauncherActivityIntent(BaseModel):
    pass


class Locale(BaseModel):
    id: Optional[str] = Field(
        None, description='The id for this locale. Example: "en_US".'
    )
    name: Optional[str] = Field(
        None,
        description='A human-friendly name for this language/locale. Example: "English".',
    )
    region: Optional[str] = Field(
        None,
        description='A human-friendly string representing the region for this locale. Example: "United States". Not present for every locale.',
    )
    tags: Optional[List[str]] = Field(
        None, description='Tags for this dimension. Example: "default".'
    )


class Metadata(BaseModel):
    name: Optional[str] = Field(None, description='The android:name value')
    value: Optional[str] = Field(None, description='The android:value value')


class ObbFile(BaseModel):
    obb: Optional[FileReference] = Field(
        None,
        description='Required. Opaque Binary Blob (OBB) file(s) to install on the device.',
    )
    obbFileName: Optional[str] = Field(
        None,
        description='Required. OBB file name which must conform to the format as specified by Android e.g. [main|patch].0300110.com.example.android.obb which will be installed into \\/Android/obb/\\/ on the device.',
    )


class Orientation(BaseModel):
    id: Optional[str] = Field(
        None, description='The id for this orientation. Example: "portrait".'
    )
    name: Optional[str] = Field(
        None,
        description='A human-friendly name for this orientation. Example: "portrait".',
    )
    tags: Optional[List[str]] = Field(
        None, description='Tags for this dimension. Example: "default".'
    )


class DeviceCapacity(Enum):
    DEVICE_CAPACITY_UNSPECIFIED = 'DEVICE_CAPACITY_UNSPECIFIED'
    DEVICE_CAPACITY_HIGH = 'DEVICE_CAPACITY_HIGH'
    DEVICE_CAPACITY_MEDIUM = 'DEVICE_CAPACITY_MEDIUM'
    DEVICE_CAPACITY_LOW = 'DEVICE_CAPACITY_LOW'
    DEVICE_CAPACITY_NONE = 'DEVICE_CAPACITY_NONE'


class PerAndroidVersionInfo(BaseModel):
    deviceCapacity: Optional[DeviceCapacity] = Field(
        None, description='The number of online devices for an Android version.'
    )
    versionId: Optional[str] = Field(None, description='An Android version.')


class PerIosVersionInfo(BaseModel):
    deviceCapacity: Optional[DeviceCapacity] = Field(
        None, description='The number of online devices for an iOS version.'
    )
    versionId: Optional[str] = Field(None, description='An iOS version.')


class ProvidedSoftwareCatalog(BaseModel):
    androidxOrchestratorVersion: Optional[str] = Field(
        None,
        description='A string representing the current version of AndroidX Test Orchestrator that is used in the environment. The package is available at https://maven.google.com/web/index.html#androidx.test:orchestrator.',
    )
    orchestratorVersion: Optional[str] = Field(
        None,
        description='Deprecated: Use AndroidX Test Orchestrator going forward. A string representing the current version of Android Test Orchestrator that is used in the environment. The package is available at https://maven.google.com/web/index.html#com.android.support.test:orchestrator.',
    )


class RegularFile(BaseModel):
    content: Optional[FileReference] = Field(
        None, description='Required. The source file.'
    )
    devicePath: Optional[str] = Field(
        None,
        description='Required. Where to put the content on the device. Must be an absolute, allowlisted path. If the file exists, it will be replaced. The following device-side directories and any of their subdirectories are allowlisted: ${EXTERNAL_STORAGE}, /sdcard, or /storage ${ANDROID_DATA}/local/tmp, or /data/local/tmp Specifying a path outside of these directory trees is invalid. The paths /sdcard and /data will be made available and treated as implicit path substitutions. E.g. if /sdcard on a particular device does not map to external storage, the system will replace it with the external storage path prefix for that device and copy the file there. It is strongly advised to use the Environment API in app and test code to access files on the device in a portable way.',
    )


class ActionType(Enum):
    ACTION_TYPE_UNSPECIFIED = 'ACTION_TYPE_UNSPECIFIED'
    SINGLE_CLICK = 'SINGLE_CLICK'
    ENTER_TEXT = 'ENTER_TEXT'
    IGNORE = 'IGNORE'


class RoboDirective(BaseModel):
    actionType: Optional[ActionType] = Field(
        None,
        description='Required. The type of action that Robo should perform on the specified element.',
    )
    inputText: Optional[str] = Field(
        None,
        description='The text that Robo is directed to set. If left empty, the directive will be treated as a CLICK on the element matching the resource_name.',
    )
    resourceName: Optional[str] = Field(
        None,
        description='Required. The android resource name of the target UI element. For example, in Java: R.string.foo in xml: @string/foo Only the "foo" part is needed. Reference doc: https://developer.android.com/guide/topics/resources/accessing-resources.html',
    )


class StartActivityIntent(BaseModel):
    action: Optional[str] = Field(
        None, description='Action name. Required for START_ACTIVITY.'
    )
    categories: Optional[List[str]] = Field(
        None, description='Intent categories to set on the intent.'
    )
    uri: Optional[str] = Field(None, description='URI for the action.')


class SystraceSetup(BaseModel):
    durationSeconds: Optional[int] = Field(
        None,
        description='Systrace duration in seconds. Should be between 1 and 30 seconds. 0 disables systrace.',
    )


class TestDetails(BaseModel):
    errorMessage: Optional[str] = Field(
        None,
        description='Output only. If the TestState is ERROR, then this string will contain human-readable details about the error.',
    )
    progressMessages: Optional[List[str]] = Field(
        None,
        description='Output only. Human-readable, detailed descriptions of the test\'s progress. For example: "Provisioning a device", "Starting Test". During the course of execution new data may be appended to the end of progress_messages.',
    )


class State(Enum):
    TEST_STATE_UNSPECIFIED = 'TEST_STATE_UNSPECIFIED'
    VALIDATING = 'VALIDATING'
    PENDING = 'PENDING'
    RUNNING = 'RUNNING'
    FINISHED = 'FINISHED'
    ERROR = 'ERROR'
    UNSUPPORTED_ENVIRONMENT = 'UNSUPPORTED_ENVIRONMENT'
    INCOMPATIBLE_ENVIRONMENT = 'INCOMPATIBLE_ENVIRONMENT'
    INCOMPATIBLE_ARCHITECTURE = 'INCOMPATIBLE_ARCHITECTURE'
    CANCELLED = 'CANCELLED'
    INVALID = 'INVALID'


class InvalidMatrixDetails(Enum):
    INVALID_MATRIX_DETAILS_UNSPECIFIED = 'INVALID_MATRIX_DETAILS_UNSPECIFIED'
    DETAILS_UNAVAILABLE = 'DETAILS_UNAVAILABLE'
    MALFORMED_APK = 'MALFORMED_APK'
    MALFORMED_TEST_APK = 'MALFORMED_TEST_APK'
    NO_MANIFEST = 'NO_MANIFEST'
    NO_PACKAGE_NAME = 'NO_PACKAGE_NAME'
    INVALID_PACKAGE_NAME = 'INVALID_PACKAGE_NAME'
    TEST_SAME_AS_APP = 'TEST_SAME_AS_APP'
    NO_INSTRUMENTATION = 'NO_INSTRUMENTATION'
    NO_SIGNATURE = 'NO_SIGNATURE'
    INSTRUMENTATION_ORCHESTRATOR_INCOMPATIBLE = (
        'INSTRUMENTATION_ORCHESTRATOR_INCOMPATIBLE'
    )
    NO_TEST_RUNNER_CLASS = 'NO_TEST_RUNNER_CLASS'
    NO_LAUNCHER_ACTIVITY = 'NO_LAUNCHER_ACTIVITY'
    FORBIDDEN_PERMISSIONS = 'FORBIDDEN_PERMISSIONS'
    INVALID_ROBO_DIRECTIVES = 'INVALID_ROBO_DIRECTIVES'
    INVALID_RESOURCE_NAME = 'INVALID_RESOURCE_NAME'
    INVALID_DIRECTIVE_ACTION = 'INVALID_DIRECTIVE_ACTION'
    TEST_LOOP_INTENT_FILTER_NOT_FOUND = 'TEST_LOOP_INTENT_FILTER_NOT_FOUND'
    SCENARIO_LABEL_NOT_DECLARED = 'SCENARIO_LABEL_NOT_DECLARED'
    SCENARIO_LABEL_MALFORMED = 'SCENARIO_LABEL_MALFORMED'
    SCENARIO_NOT_DECLARED = 'SCENARIO_NOT_DECLARED'
    DEVICE_ADMIN_RECEIVER = 'DEVICE_ADMIN_RECEIVER'
    MALFORMED_XC_TEST_ZIP = 'MALFORMED_XC_TEST_ZIP'
    BUILT_FOR_IOS_SIMULATOR = 'BUILT_FOR_IOS_SIMULATOR'
    NO_TESTS_IN_XC_TEST_ZIP = 'NO_TESTS_IN_XC_TEST_ZIP'
    USE_DESTINATION_ARTIFACTS = 'USE_DESTINATION_ARTIFACTS'
    TEST_NOT_APP_HOSTED = 'TEST_NOT_APP_HOSTED'
    PLIST_CANNOT_BE_PARSED = 'PLIST_CANNOT_BE_PARSED'
    TEST_ONLY_APK = 'TEST_ONLY_APK'
    MALFORMED_IPA = 'MALFORMED_IPA'
    MISSING_URL_SCHEME = 'MISSING_URL_SCHEME'
    MALFORMED_APP_BUNDLE = 'MALFORMED_APP_BUNDLE'
    NO_CODE_APK = 'NO_CODE_APK'
    INVALID_INPUT_APK = 'INVALID_INPUT_APK'
    INVALID_APK_PREVIEW_SDK = 'INVALID_APK_PREVIEW_SDK'
    MATRIX_TOO_LARGE = 'MATRIX_TOO_LARGE'
    TEST_QUOTA_EXCEEDED = 'TEST_QUOTA_EXCEEDED'
    SERVICE_NOT_ACTIVATED = 'SERVICE_NOT_ACTIVATED'
    UNKNOWN_PERMISSION_ERROR = 'UNKNOWN_PERMISSION_ERROR'


class OutcomeSummary(Enum):
    OUTCOME_SUMMARY_UNSPECIFIED = 'OUTCOME_SUMMARY_UNSPECIFIED'
    SUCCESS = 'SUCCESS'
    FAILURE = 'FAILURE'
    INCONCLUSIVE = 'INCONCLUSIVE'
    SKIPPED = 'SKIPPED'


class TestTargetsForShard(BaseModel):
    testTargets: Optional[List[str]] = Field(
        None,
        description='Group of packages, classes, and/or test methods to be run for each shard. The targets need to be specified in AndroidJUnitRunner argument format. For example, "package com.my.packages" "class com.my.package.MyClass". The number of test_targets must be greater than 0.',
    )


class ToolResultsExecution(BaseModel):
    executionId: Optional[str] = Field(
        None, description='Output only. A tool results execution ID.'
    )
    historyId: Optional[str] = Field(
        None, description='Output only. A tool results history ID.'
    )
    projectId: Optional[str] = Field(
        None,
        description='Output only. The cloud project that owns the tool results execution.',
    )


class ToolResultsHistory(BaseModel):
    historyId: Optional[str] = Field(
        None, description='Required. A tool results history ID.'
    )
    projectId: Optional[str] = Field(
        None,
        description='Required. The cloud project that owns the tool results history.',
    )


class ToolResultsStep(BaseModel):
    executionId: Optional[str] = Field(
        None, description='Output only. A tool results execution ID.'
    )
    historyId: Optional[str] = Field(
        None, description='Output only. A tool results history ID.'
    )
    projectId: Optional[str] = Field(
        None,
        description='Output only. The cloud project that owns the tool results step.',
    )
    stepId: Optional[str] = Field(
        None, description='Output only. A tool results step ID.'
    )


class TrafficRule(BaseModel):
    bandwidth: Optional[float] = Field(None, description='Bandwidth in kbits/second.')
    burst: Optional[float] = Field(None, description='Burst size in kbits.')
    delay: Optional[str] = Field(None, description='Packet delay, must be >= 0.')
    packetDuplicationRatio: Optional[float] = Field(
        None, description='Packet duplication ratio (0.0 - 1.0).'
    )
    packetLossRatio: Optional[float] = Field(
        None, description='Packet loss ratio (0.0 - 1.0).'
    )


class UniformSharding(BaseModel):
    numShards: Optional[int] = Field(
        None,
        description='Required. The total number of shards to create. This must always be a positive number that is no greater than the total number of test cases. When you select one or more physical devices, the number of shards must be <= 50. When you select one or more ARM virtual devices, it must be <= 100. When you select only x86 virtual devices, it must be <= 500.',
    )


class UsesFeature(BaseModel):
    isRequired: Optional[bool] = Field(None, description='The android:required value')
    name: Optional[str] = Field(None, description='The android:name value')


class XcodeVersion(BaseModel):
    tags: Optional[List[str]] = Field(
        None, description='Tags for this Xcode version. Example: "default".'
    )
    version: Optional[str] = Field(
        None, description='The id for this version. Example: "9.2".'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class EnvironmentType(Enum):
    ENVIRONMENT_TYPE_UNSPECIFIED = 'ENVIRONMENT_TYPE_UNSPECIFIED'
    ANDROID = 'ANDROID'
    IOS = 'IOS'
    NETWORK_CONFIGURATION = 'NETWORK_CONFIGURATION'
    PROVIDED_SOFTWARE = 'PROVIDED_SOFTWARE'
    DEVICE_IP_BLOCKS = 'DEVICE_IP_BLOCKS'


class Account(BaseModel):
    googleAuto: Optional[GoogleAuto] = Field(
        None, description='An automatic google login account.'
    )


class AndroidModel(BaseModel):
    brand: Optional[str] = Field(
        None,
        description='The company that this device is branded with. Example: "Google", "Samsung".',
    )
    codename: Optional[str] = Field(
        None,
        description='The name of the industrial design. This corresponds to android.os.Build.DEVICE.',
    )
    form: Optional[Form] = Field(
        None, description='Whether this device is virtual or physical.'
    )
    formFactor: Optional[FormFactor] = Field(
        None, description='Whether this device is a phone, tablet, wearable, etc.'
    )
    id: Optional[str] = Field(
        None,
        description='The unique opaque id for this model. Use this for invoking the TestExecutionService.',
    )
    lowFpsVideoRecording: Optional[bool] = Field(
        None,
        description='True if and only if tests with this model are recorded by stitching together screenshots. See use_low_spec_video_recording in device config.',
    )
    manufacturer: Optional[str] = Field(
        None, description='The manufacturer of this device.'
    )
    name: Optional[str] = Field(
        None,
        description='The human-readable marketing name for this device model. Examples: "Nexus 5", "Galaxy S5".',
    )
    perVersionInfo: Optional[List[PerAndroidVersionInfo]] = Field(
        None, description='Version-specific information of an Android model.'
    )
    screenDensity: Optional[int] = Field(
        None, description='Screen density in DPI. This corresponds to ro.sf.lcd_density'
    )
    screenX: Optional[int] = Field(
        None,
        description='Screen size in the horizontal (X) dimension measured in pixels.',
    )
    screenY: Optional[int] = Field(
        None,
        description='Screen size in the vertical (Y) dimension measured in pixels.',
    )
    supportedAbis: Optional[List[str]] = Field(
        None,
        description='The list of supported ABIs for this device. This corresponds to either android.os.Build.SUPPORTED_ABIS (for API level 21 and above) or android.os.Build.CPU_ABI/CPU_ABI2. The most preferred ABI is the first element in the list. Elements are optionally prefixed by "version_id:" (where version_id is the id of an AndroidVersion), denoting an ABI that is supported only on a particular version.',
    )
    supportedVersionIds: Optional[List[str]] = Field(
        None, description='The set of Android versions this device supports.'
    )
    tags: Optional[List[str]] = Field(
        None,
        description='Tags for this dimension. Examples: "default", "preview", "deprecated".',
    )
    thumbnailUrl: Optional[str] = Field(
        None, description='URL of a thumbnail image (photo) of the device.'
    )


class AndroidRuntimeConfiguration(BaseModel):
    locales: Optional[List[Locale]] = Field(
        None, description='The set of available locales.'
    )
    orientations: Optional[List[Orientation]] = Field(
        None, description='The set of available orientations.'
    )


class AndroidVersion(BaseModel):
    apiLevel: Optional[int] = Field(
        None, description='The API level for this Android version. Examples: 18, 19.'
    )
    codeName: Optional[str] = Field(
        None,
        description='The code name for this Android version. Examples: "JellyBean", "KitKat".',
    )
    distribution: Optional[Distribution] = Field(
        None, description='Market share for this version.'
    )
    id: Optional[str] = Field(
        None,
        description='An opaque id for this Android version. Use this id to invoke the TestExecutionService.',
    )
    releaseDate: Optional[Date] = Field(
        None,
        description='The date this Android version became available in the market.',
    )
    tags: Optional[List[str]] = Field(
        None,
        description='Tags for this dimension. Examples: "default", "preview", "deprecated".',
    )
    versionString: Optional[str] = Field(
        None,
        description='A string representing this version of the Android OS. Examples: "4.3", "4.4".',
    )


class Apk(BaseModel):
    location: Optional[FileReference] = Field(
        None,
        description='The path to an APK to be installed on the device before the test begins.',
    )
    packageName: Optional[str] = Field(
        None,
        description="The java package for the APK to be installed. Value is determined by examining the application's manifest.",
    )


class ApkManifest(BaseModel):
    applicationLabel: Optional[str] = Field(
        None, description='User-readable name for the application.'
    )
    intentFilters: Optional[List[IntentFilter]] = None
    maxSdkVersion: Optional[int] = Field(
        None,
        description='Maximum API level on which the application is designed to run.',
    )
    metadata: Optional[List[Metadata]] = Field(
        None, description='Meta-data tags defined in the manifest.'
    )
    minSdkVersion: Optional[int] = Field(
        None, description='Minimum API level required for the application to run.'
    )
    packageName: Optional[str] = Field(
        None,
        description='Full Java-style package name for this application, e.g. "com.example.foo".',
    )
    targetSdkVersion: Optional[int] = Field(
        None,
        description='Specifies the API Level on which the application is designed to run.',
    )
    usesFeature: Optional[List[UsesFeature]] = Field(
        None, description='Feature usage tags defined in the manifest.'
    )
    usesPermission: Optional[List[str]] = Field(
        None, description='Permissions declared to be used by the application'
    )
    versionCode: Optional[str] = Field(
        None, description='Version number used internally by the app.'
    )
    versionName: Optional[str] = Field(
        None, description='Version number shown to users.'
    )


class AppBundle(BaseModel):
    bundleLocation: Optional[FileReference] = Field(
        None, description='.aab file representing the app bundle under test.'
    )


class ClientInfo(BaseModel):
    clientInfoDetails: Optional[List[ClientInfoDetail]] = Field(
        None, description='The list of detailed information about client.'
    )
    name: Optional[str] = Field(
        None, description='Required. Client name, such as gcloud.'
    )


class DeviceFile(BaseModel):
    obbFile: Optional[ObbFile] = Field(
        None, description='A reference to an opaque binary blob file.'
    )
    regularFile: Optional[RegularFile] = Field(
        None, description='A reference to a regular file.'
    )


class Environment(BaseModel):
    androidDevice: Optional[AndroidDevice] = Field(
        None, description='An Android device which must be used with an Android test.'
    )
    iosDevice: Optional[IosDevice] = Field(
        None, description='An iOS device which must be used with an iOS test.'
    )


class EnvironmentMatrix(BaseModel):
    androidDeviceList: Optional[AndroidDeviceList] = Field(
        None,
        description='A list of Android devices; the test will be run only on the specified devices.',
    )
    androidMatrix: Optional[AndroidMatrix] = Field(
        None, description='A matrix of Android devices.'
    )
    iosDeviceList: Optional[IosDeviceList] = Field(
        None, description='A list of iOS devices.'
    )


class IosModel(BaseModel):
    deviceCapabilities: Optional[List[str]] = Field(
        None,
        description='Device capabilities. Copied from https://developer.apple.com/library/archive/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/DeviceCompatibilityMatrix/DeviceCompatibilityMatrix.html',
    )
    formFactor: Optional[FormFactor] = Field(
        None, description='Whether this device is a phone, tablet, wearable, etc.'
    )
    id: Optional[str] = Field(
        None,
        description='The unique opaque id for this model. Use this for invoking the TestExecutionService.',
    )
    name: Optional[str] = Field(
        None,
        description='The human-readable name for this device model. Examples: "iPhone 4s", "iPad Mini 2".',
    )
    perVersionInfo: Optional[List[PerIosVersionInfo]] = Field(
        None, description='Version-specific information of an iOS model.'
    )
    screenDensity: Optional[int] = Field(None, description='Screen density in DPI.')
    screenX: Optional[int] = Field(
        None,
        description='Screen size in the horizontal (X) dimension measured in pixels.',
    )
    screenY: Optional[int] = Field(
        None,
        description='Screen size in the vertical (Y) dimension measured in pixels.',
    )
    supportedVersionIds: Optional[List[str]] = Field(
        None, description='The set of iOS major software versions this device supports.'
    )
    tags: Optional[List[str]] = Field(
        None,
        description='Tags for this dimension. Examples: "default", "preview", "deprecated".',
    )


class IosRuntimeConfiguration(BaseModel):
    locales: Optional[List[Locale]] = Field(
        None, description='The set of available locales.'
    )
    orientations: Optional[List[Orientation]] = Field(
        None, description='The set of available orientations.'
    )


class ManualSharding(BaseModel):
    testTargetsForShard: Optional[List[TestTargetsForShard]] = Field(
        None,
        description='Required. Group of packages, classes, and/or test methods to be run for each manually-created shard. You must specify at least one shard if this field is present. When you select one or more physical devices, the number of repeated test_targets_for_shard must be <= 50. When you select one or more ARM virtual devices, it must be <= 100. When you select only x86 virtual devices, it must be <= 500.',
    )


class NetworkConfiguration(BaseModel):
    downRule: Optional[TrafficRule] = Field(
        None, description='The emulation rule applying to the download traffic.'
    )
    id: Optional[str] = Field(
        None, description='The unique opaque id for this network traffic configuration.'
    )
    upRule: Optional[TrafficRule] = Field(
        None, description='The emulation rule applying to the upload traffic.'
    )


class NetworkConfigurationCatalog(BaseModel):
    configurations: Optional[List[NetworkConfiguration]] = None


class ResultStorage(BaseModel):
    googleCloudStorage: Optional[GoogleCloudStorage] = Field(
        None, description='Required.'
    )
    resultsUrl: Optional[str] = Field(
        None, description='Output only. URL to the results in the Firebase Web Console.'
    )
    toolResultsExecution: Optional[ToolResultsExecution] = Field(
        None,
        description='Output only. The tool results execution that results are written to.',
    )
    toolResultsHistory: Optional[ToolResultsHistory] = Field(
        None,
        description='The tool results history that contains the tool results execution that results are written to. If not provided, the service will choose an appropriate value.',
    )


class RoboStartingIntent(BaseModel):
    launcherActivity: Optional[LauncherActivityIntent] = Field(
        None, description='An intent that starts the main launcher activity.'
    )
    startActivity: Optional[StartActivityIntent] = Field(
        None, description='An intent that starts an activity with specific details.'
    )
    timeout: Optional[str] = Field(
        None, description='Timeout in seconds for each intent.'
    )


class Shard(BaseModel):
    numShards: Optional[int] = Field(
        None, description='Output only. The total number of shards.'
    )
    shardIndex: Optional[int] = Field(
        None, description='Output only. The index of the shard among all the shards.'
    )
    testTargetsForShard: Optional[TestTargetsForShard] = Field(
        None,
        description='Output only. Test targets for each shard. Only set for manual sharding.',
    )


class ShardingOption(BaseModel):
    manualSharding: Optional[ManualSharding] = Field(
        None,
        description='Shards test cases into the specified groups of packages, classes, and/or methods.',
    )
    uniformSharding: Optional[UniformSharding] = Field(
        None, description='Uniformly shards test cases given a total number of shards.'
    )


class TestSetup(BaseModel):
    account: Optional[Account] = Field(
        None,
        description='The device will be logged in on this account for the duration of the test.',
    )
    additionalApks: Optional[List[Apk]] = Field(
        None,
        description='APKs to install in addition to those being directly tested. Currently capped at 100.',
    )
    directoriesToPull: Optional[List[str]] = Field(
        None,
        description='List of directories on the device to upload to GCS at the end of the test; they must be absolute paths under /sdcard, /storage or /data/local/tmp. Path names are restricted to characters a-z A-Z 0-9 _ - . + and / Note: The paths /sdcard and /data will be made available and treated as implicit path substitutions. E.g. if /sdcard on a particular device does not map to external storage, the system will replace it with the external storage path prefix for that device.',
    )
    dontAutograntPermissions: Optional[bool] = Field(
        None,
        description='Whether to prevent all runtime permissions to be granted at app install',
    )
    environmentVariables: Optional[List[EnvironmentVariable]] = Field(
        None,
        description='Environment variables to set for the test (only applicable for instrumentation tests).',
    )
    filesToPush: Optional[List[DeviceFile]] = Field(
        None,
        description='List of files to push to the device before starting the test.',
    )
    networkProfile: Optional[str] = Field(
        None,
        description='The network traffic profile used for running the test. Available network profiles can be queried by using the NETWORK_CONFIGURATION environment type when calling TestEnvironmentDiscoveryService.GetTestEnvironmentCatalog.',
    )
    systrace: Optional[SystraceSetup] = Field(
        None,
        description='Systrace configuration for the run. Deprecated: Systrace used Python 2 which was sunsetted on 2020-01-01. Systrace is no longer supported in the Cloud Testing API, and no Systrace file will be provided in the results.',
    )


class AndroidDeviceCatalog(BaseModel):
    models: Optional[List[AndroidModel]] = Field(
        None, description='The set of supported Android device models.'
    )
    runtimeConfiguration: Optional[AndroidRuntimeConfiguration] = Field(
        None, description='The set of supported runtime configurations.'
    )
    versions: Optional[List[AndroidVersion]] = Field(
        None, description='The set of supported Android OS versions.'
    )


class AndroidInstrumentationTest(BaseModel):
    appApk: Optional[FileReference] = Field(
        None, description='The APK for the application under test.'
    )
    appBundle: Optional[AppBundle] = Field(
        None, description='A multi-apk app bundle for the application under test.'
    )
    appPackageId: Optional[str] = Field(
        None,
        description="The java package for the application under test. The default value is determined by examining the application's manifest.",
    )
    orchestratorOption: Optional[OrchestratorOption] = Field(
        None,
        description='The option of whether running each test within its own invocation of instrumentation with Android Test Orchestrator or not. ** Orchestrator is only compatible with AndroidJUnitRunner version 1.1 or higher! ** Orchestrator offers the following benefits: - No shared state - Crashes are isolated - Logs are scoped per test See for more information about Android Test Orchestrator. If not set, the test will be run without the orchestrator.',
    )
    shardingOption: Optional[ShardingOption] = Field(
        None, description='The option to run tests in multiple shards in parallel.'
    )
    testApk: Optional[FileReference] = Field(
        None, description='Required. The APK containing the test code to be executed.'
    )
    testPackageId: Optional[str] = Field(
        None,
        description="The java package for the test to be executed. The default value is determined by examining the application's manifest.",
    )
    testRunnerClass: Optional[str] = Field(
        None,
        description="The InstrumentationTestRunner class. The default value is determined by examining the application's manifest.",
    )
    testTargets: Optional[List[str]] = Field(
        None,
        description='Each target must be fully qualified with the package name or class name, in one of these formats: - "package package_name" - "class package_name.class_name" - "class package_name.class_name#method_name" If empty, all targets in the module will be run.',
    )


class AndroidRoboTest(BaseModel):
    appApk: Optional[FileReference] = Field(
        None, description='The APK for the application under test.'
    )
    appBundle: Optional[AppBundle] = Field(
        None, description='A multi-apk app bundle for the application under test.'
    )
    appInitialActivity: Optional[str] = Field(
        None, description='The initial activity that should be used to start the app.'
    )
    appPackageId: Optional[str] = Field(
        None,
        description="The java package for the application under test. The default value is determined by examining the application's manifest.",
    )
    maxDepth: Optional[int] = Field(
        None,
        description='The max depth of the traversal stack Robo can explore. Needs to be at least 2 to make Robo explore the app beyond the first activity. Default is 50.',
    )
    maxSteps: Optional[int] = Field(
        None,
        description='The max number of steps Robo can execute. Default is no limit.',
    )
    roboDirectives: Optional[List[RoboDirective]] = Field(
        None,
        description='A set of directives Robo should apply during the crawl. This allows users to customize the crawl. For example, the username and password for a test account can be provided.',
    )
    roboMode: Optional[RoboMode] = Field(
        None,
        description='The mode in which Robo should run. Most clients should allow the server to populate this field automatically.',
    )
    roboScript: Optional[FileReference] = Field(
        None,
        description='A JSON file with a sequence of actions Robo should perform as a prologue for the crawl.',
    )
    startingIntents: Optional[List[RoboStartingIntent]] = Field(
        None,
        description='The intents used to launch the app for the crawl. If none are provided, then the main launcher activity is launched. If some are provided, then only those provided are launched (the main launcher activity must be provided explicitly).',
    )


class AndroidTestLoop(BaseModel):
    appApk: Optional[FileReference] = Field(
        None, description='The APK for the application under test.'
    )
    appBundle: Optional[AppBundle] = Field(
        None, description='A multi-apk app bundle for the application under test.'
    )
    appPackageId: Optional[str] = Field(
        None,
        description="The java package for the application under test. The default is determined by examining the application's manifest.",
    )
    scenarioLabels: Optional[List[str]] = Field(
        None,
        description="The list of scenario labels that should be run during the test. The scenario labels should map to labels defined in the application's manifest. For example, player_experience and com.google.test.loops.player_experience add all of the loops labeled in the manifest with the com.google.test.loops.player_experience name to the execution. Scenarios can also be specified in the scenarios field.",
    )
    scenarios: Optional[List[int]] = Field(
        None,
        description="The list of scenarios that should be run during the test. The default is all test loops, derived from the application's manifest.",
    )


class ApkDetail(BaseModel):
    apkManifest: Optional[ApkManifest] = None


class GetApkDetailsResponse(BaseModel):
    apkDetail: Optional[ApkDetail] = Field(
        None, description='Details of the Android APK.'
    )


class IosDeviceCatalog(BaseModel):
    models: Optional[List[IosModel]] = Field(
        None, description='The set of supported iOS device models.'
    )
    runtimeConfiguration: Optional[IosRuntimeConfiguration] = Field(
        None, description='The set of supported runtime configurations.'
    )
    versions: Optional[List[IosVersion]] = Field(
        None, description='The set of supported iOS software versions.'
    )
    xcodeVersions: Optional[List[XcodeVersion]] = Field(
        None, description='The set of supported Xcode versions.'
    )


class TestEnvironmentCatalog(BaseModel):
    androidDeviceCatalog: Optional[AndroidDeviceCatalog] = Field(
        None, description='Supported Android devices.'
    )
    deviceIpBlockCatalog: Optional[DeviceIpBlockCatalog] = Field(
        None, description='The IP blocks used by devices in the test environment.'
    )
    iosDeviceCatalog: Optional[IosDeviceCatalog] = Field(
        None, description='Supported iOS devices.'
    )
    networkConfigurationCatalog: Optional[NetworkConfigurationCatalog] = Field(
        None, description='Supported network configurations.'
    )
    softwareCatalog: Optional[ProvidedSoftwareCatalog] = Field(
        None,
        description='The software test environment provided by TestExecutionService.',
    )


class TestSpecification(BaseModel):
    androidInstrumentationTest: Optional[AndroidInstrumentationTest] = Field(
        None, description='An Android instrumentation test.'
    )
    androidRoboTest: Optional[AndroidRoboTest] = Field(
        None, description='An Android robo test.'
    )
    androidTestLoop: Optional[AndroidTestLoop] = Field(
        None, description='An Android Application with a Test Loop.'
    )
    disablePerformanceMetrics: Optional[bool] = Field(
        None,
        description='Disables performance metrics recording. May reduce test latency.',
    )
    disableVideoRecording: Optional[bool] = Field(
        None, description='Disables video recording. May reduce test latency.'
    )
    iosTestLoop: Optional[IosTestLoop] = Field(
        None, description='An iOS application with a test loop.'
    )
    iosTestSetup: Optional[IosTestSetup] = Field(
        None, description='Test setup requirements for iOS.'
    )
    iosXcTest: Optional[IosXcTest] = Field(
        None, description='An iOS XCTest, via an .xctestrun file.'
    )
    testSetup: Optional[TestSetup] = Field(
        None,
        description='Test setup requirements for Android e.g. files to install, bootstrap scripts.',
    )
    testTimeout: Optional[str] = Field(
        None,
        description='Max time a test execution is allowed to run before it is automatically cancelled. The default value is 5 min.',
    )


class TestExecution(BaseModel):
    environment: Optional[Environment] = Field(
        None, description='Output only. How the host machine(s) are configured.'
    )
    id: Optional[str] = Field(
        None, description='Output only. Unique id set by the service.'
    )
    matrixId: Optional[str] = Field(
        None, description='Output only. Id of the containing TestMatrix.'
    )
    projectId: Optional[str] = Field(
        None, description='Output only. The cloud project that owns the test execution.'
    )
    shard: Optional[Shard] = Field(
        None, description='Output only. Details about the shard.'
    )
    state: Optional[State] = Field(
        None,
        description='Output only. Indicates the current progress of the test execution (e.g., FINISHED).',
    )
    testDetails: Optional[TestDetails] = Field(
        None, description='Output only. Additional details about the running test.'
    )
    testSpecification: Optional[TestSpecification] = Field(
        None, description='Output only. How to run the test.'
    )
    timestamp: Optional[str] = Field(
        None,
        description='Output only. The time this test execution was initially created.',
    )
    toolResultsStep: Optional[ToolResultsStep] = Field(
        None,
        description='Output only. Where the results for this execution are written.',
    )


class TestMatrix(BaseModel):
    clientInfo: Optional[ClientInfo] = Field(
        None, description='Information about the client which invoked the test.'
    )
    environmentMatrix: Optional[EnvironmentMatrix] = Field(
        None, description='Required. The devices the tests are being executed on.'
    )
    failFast: Optional[bool] = Field(
        None,
        description='If true, only a single attempt at most will be made to run each execution/shard in the matrix. Flaky test attempts are not affected. Normally, 2 or more attempts are made if a potential infrastructure issue is detected. This feature is for latency sensitive workloads. The incidence of execution failures may be significantly greater for fail-fast matrices and support is more limited because of that expectation.',
    )
    flakyTestAttempts: Optional[int] = Field(
        None,
        description='The number of times a TestExecution should be re-attempted if one or more of its test cases fail for any reason. The maximum number of reruns allowed is 10. Default is 0, which implies no reruns.',
    )
    invalidMatrixDetails: Optional[InvalidMatrixDetails] = Field(
        None,
        description='Output only. Describes why the matrix is considered invalid. Only useful for matrices in the INVALID state.',
    )
    outcomeSummary: Optional[OutcomeSummary] = Field(
        None,
        description='Output Only. The overall outcome of the test. Only set when the test matrix state is FINISHED.',
    )
    projectId: Optional[str] = Field(
        None, description='The cloud project that owns the test matrix.'
    )
    resultStorage: Optional[ResultStorage] = Field(
        None, description='Required. Where the results for the matrix are written.'
    )
    state: Optional[State] = Field(
        None,
        description='Output only. Indicates the current progress of the test matrix.',
    )
    testExecutions: Optional[List[TestExecution]] = Field(
        None,
        description='Output only. The list of test executions that the service creates for this matrix.',
    )
    testMatrixId: Optional[str] = Field(
        None, description='Output only. Unique id set by the service.'
    )
    testSpecification: Optional[TestSpecification] = Field(
        None, description='Required. How to run the test.'
    )
    timestamp: Optional[str] = Field(
        None,
        description='Output only. The time this test matrix was initially created.',
    )
